name: Lint Python Code

on: [push, pull_request]

jobs:
lint:
 runs-on: ubuntu-latest

 steps:
 -name: Checkout code
 users: actions/checkout@v3

 -name: Set up Python 
 uses:
actions/setup-python@v4
with:
python-versiopn: '3.x'

-name: Install Pycodestyle
run: |
pip install pycodestyle

-name: Lint Python files with Pycodestyle
run: |
pycodestlyle